version: "3"

services:
  web:
    build: .
    container_name: vaultpoint_sample_client
    hostname: nestjs_app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: vaultpoint_pg_database
    hostname: pg_db
    volumes:
      - ~/docker-volumes/vaultpoint_client_postgres:/var/lib/postgresql/data
    env_file:
      - env/pg.env
    ports:
      - "5432:5432"
